<Project>
  <PropertyGroup>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <XmPlaylistBuildDirectory>$(MSBuildThisFileDirectory)_build</XmPlaylistBuildDirectory>
    <XmPlaylistPluginOutputDirectory>$(MSBuildThisFileDirectory)_plugins\$(TargetFramework)\$(MSBuildProjectName)</XmPlaylistPluginOutputDirectory>
  </PropertyGroup>
</Project>
